routes/web.php
<?php
use Symfony\Component\HttpFoundation\Response;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
*/

Route::view('/', 'landing');

Auth::routes();

Route::group(['middleware' => ['auth']], function () { //MIDDLEWARE
Route::get('home', 'HomeController@index');
Route::prefix('dash')->group(function () {
 	Route::get('/', 'HomeController@index')->name('dash'); 
 	Route::get('search', 'PublicationController@search')->name('search');
 	Route::get('brands/{bran_id?}', 'HomeController@viewAll')->name('brands');
 	Route::get('models/{model_id}', 'HomeController@viewModel')->name('models');

	Route::resource('publications', 'PublicationController'); 
	Route::get('publication/newcreate', 'PublicationController@newCreate'); 
	Route::get('publication/{publication_id}/deleting', 'PublicationController@destroy');
	Route::get('publication/{publication_id}/sold', 'PublicationController@sold'); 
	Route::get('publication/showversions', 'PublicationController@showVersions'); 
	Route::get('publication/byversion/{version_id}', 'PublicationController@publicationsByVersion');

	Route::post('searchpublications', 'PublicationController@searchPublications');   
	Route::resource('averages', 'AverageController');
	Route::resource('versions', 'VersionController');  
	Route::get('version/view/{bran_id?}', 'VersionController@viewAll');  
	Route::resource('subversions', 'SubversionController');  
	Route::get('versions/model/{model}', 'VersionController@searchByModel'); 
	Route::get('versions/{version}/model/{model}/subversions', 'VersionController@searchSubversions'); 
	Route::get('versions/model/{model}/subversions/hiddingtakens', 'VersionController@searchSubversionsHT'); 
	Route::get('versions/{version_id}/publications', 'AverageController@tagPublications');  
	Route::post('versions/subversion/create', 'SubversionController@storeAjax');
	Route::get('versions/{version}/subversion/{name}/delete', 'SubversionController@deleteAjax');
	Route::get('models/brand/{brand}', 'PublicationController@searchByBrand');
	Route::post('publications/search', 'PublicationController@results');
	Route::get('publications/more/attr/{id_model}/{version_id}', 'VersionController@getMoreattr');



	//HELPERS AJAX
	Route::get('helper/get_versions/{model}', 'VersionController@getVersionsByModel');
	Route::get('helper/has_pub/{cat}', function($cat) { return hasPub($cat); });
	Route::get('helper/get_all_pub/{brand}/{model}/{ajax?}', function($brand,$model,$ajax='true') {  
		$publications = getAllPub($model); 
		if ($ajax == 'true') {  
			if ($publications) {
				$q=storeUpdatePublications($brand,$publications);
				return response()->json(['status'=>true,'data'=>$q]);
			}else{
				return response()->json(['status'=>false]);
			} 
		}else{ 
			dd(($publications)? storeUpdatePublications($brand,$publications):$publications);
		} 
	});
	
	
    //USERS
	Route::resource('users', 'UserController');
});//END DASH
});//END MIDDLEWARE

app/Publication.php
<?php

namespace App;
use App\Average;
use App\Range;
use Illuminate\Database\Eloquent\Model;

class Publication extends Model
{
	protected $fillable = [
        'title',
        'id_ML',
        'price',
        'brand_id',
        'model_id',
        'realtrim', 
        'listing_type_id',
        'stop_time',
        'permalink',
        'thumbnail',
        'state_name',
        'city_name',
        'original_price',
        'available_quantity',
        'sold_quantity',
        'buying_mode', 
        'BRAND',
        'MODEL',
        'DOORS',
        'FUEL_TYPE',
        'KILOMETERS',
        'TRANSMISSION',
        'TRIM',
        'VEHICLE_YEAR',
        'ENGINE_DISPLACEMENT',
        'TRACTION_CONTROL',
        'ITEM_CONDITION',
        'sold',
        'sold_date',
        'AIRE',
        'BAROMETER'
    ];

    public function attributes()
    {
        return $this->belongsToMany(Attribute::class, 'attribute_publication')->withPivot(["value_name"]);
    }
    public function getRealPriceAttribute()
    {
        $price = ($this->price);
        $price = round($price,2);

    	$realprice = '$'.number_format ( $price, 0 , "," , "." );
        return $realprice;
    }
    public function getRealBrandAttribute()
    {
    	$attribute = $this->attributes()->where('value_id','BRAND')->get();
        if(isset($attribute[0]) && $attribute[0]!=null)
    	   return $attribute[0]['pivot']['value_name'];
    }
    public function getRealModelAttribute()
    {
    	$attribute = $this->attributes()->where('value_id','MODEL')->get();
        if(isset($attribute[0]) && $attribute[0]!=null)
    	   return $attribute[0]['pivot']['value_name'];
    }
    public function getRealYearAttribute()
    {
    	$attribute = $this->attributes()->where('value_id','VEHICLE_YEAR')->get();
        if(isset($attribute[0]) && $attribute[0]!=null)
    	   return $attribute[0]['pivot']['value_name'];
    }
    public function getRealKMAttribute()
    {
        $attribute = $this->KILOMETERS;
        if(isset($attribute[0]) && $attribute[0]!=null){
            $realkm = str_replace(' km', "", $attribute);
            return $realkm;
        }
    }
    public function getRealTransmissionAttribute()
    {
        $attribute = $this->attributes()->where('value_id','TRANSMISSION')->get();
        if(isset($attribute[0]) && $attribute[0]!=null){
            return $attribute[0]['pivot']['value_name'];
        }
    }
    public function getRealDoorsAttribute()
    {
        $attribute = $this->attributes()->where('value_id','DOORS')->get();
        if(isset($attribute[0]) && $attribute[0]!=null){
            return $attribute[0]['pivot']['value_name'];
        }
    }

    public function getBarometroAttribute($params=false)
    {    
        $ptBarometro=0;
        if (!$params) {
            $params = [
                'ml_average' => 60,
                'ml_average_km' => 20,
                'average_expected_km' => 20,
            ];  
        }  
        foreach ($params as $key => $peso) {   
            $value = $this->histories->last()->$key; 
            $avarageBar = (($peso*abs($value))/100);
            $ptBarometro += $avarageBar;  
        }  
        return $ptBarometro;
    }

    public function getJustTrimAttribute()
    {
        $realtrim = $this->realtrim;
        $JustTrim = explode('-', $realtrim, 2);
        if(isset($JustTrim[1])){
            return $JustTrim[1];
        }else{
            return '--';
        }
        
    }
    public function getRealVersionAttribute()
    { 
        if(isset($this->TRIM) && $this->TRIM!=null){
            $realversion = strtoupper($this->TRIM);
            // $realversion = str_replace(strtoupper($this->RealModel).' ', ".", $realversion);
            // $realversion = str_replace(strtoupper($this->RealYear).' ', ".", $realversion);
            // $realversion = str_replace(strtoupper($this->RealBrand).' ', ".", $realversion);
            // $realversion = str_replace(strtoupper(' '.$this->RealModel), "/", $realversion);
            // $realversion = str_replace(strtoupper(' '.$this->RealYear), "/", $realversion);
            // $realversion = str_replace(strtoupper(' '.$this->RealBrand), "/", $realversion);
            $realversion = str_replace(strtoupper('ALL'), ".", $realversion);
            $realversion = str_replace(strtoupper('NEW'), ".", $realversion);
            $realversion = str_replace(strtoupper('VIDRIOS'), ".", $realversion);
            $realversion = str_replace(strtoupper('ELECTRIC'), ".", $realversion);
            $realversion = str_replace(strtoupper('ELECTRICO'), ".", $realversion);
            $realversion = str_replace(strtoupper('EQUIPO'), ".", $realversion);
            $realversion = str_replace(strtoupper('FULL'), ".", $realversion);
            $realversion = str_replace(strtoupper('SUN'), ".", $realversion);
            $realversion = str_replace(strtoupper('ROOF'), ".", $realversion);
            $realversion = str_replace(strtoupper('VERSION'), ".", $realversion);
            $realversion = str_replace(strtoupper('CC'), "", $realversion);
            $realversion = str_replace(',', "", $realversion);
            $realversion = str_replace("/", "", $realversion);
            $realversion = str_replace(" .", "", $realversion);
            $realversion = str_replace(". ", "", $realversion);
            $realversion = str_replace(".", "", $realversion);
            $realversion = str_replace("-", "", $realversion);
            $realversion = str_replace(" ", "-", $realversion);
            $realversion = str_replace("---", "-", $realversion);
            $realversion = str_replace("--", "-", $realversion);
           return $realversion;
        }
    }
    public function getFullBrandModelAttribute()
    {
        return $this->RealBrand.' - '.$this->RealModel.' - '.$this->RealYear;
    }

    public function histories() {
        return $this->hasMany('App\History');
    }

    public function last_history() {
        return $this->hasMany('App\History')->limit(1);
    }

    public function getRealRangeAttribute() {
        $return = $this->histories->last()->ml_average_km_tooltip;
        $return = str_replace("<em>", "", $return);
        $return = str_replace("</em>", "", $return);
        $return = str_replace("milKM","", $return);
        $return = explode("<br>", $return);
        $return = explode("~", $return[0]);
        $return = $return[0];
        // $return = str_replace("N/A", "99999", $return); 
        // if($return[0]=='0 - 10'){
        //     return "";
        // }
        return $return; 
    }

    //AVERAGES 

    // public function getMlAverageAttribute()
    // {
    //     $average = Average::all()->where('realtrim', $this->realtrim)->where('year',$this->RealYear)->last();
    //     $return = 'N/A';
    //     if ($average == null || $average->promedio_ml==0) {
    //         $return = 'N/A';
    //     }else{
    //             $average=$average->promedio_ml;
    //             $price =  $this->price;
    //             $return = ((round(($price*100)/$average))-100).'%';
    //     }

    //     return  $return;
    // }
    // public function getMlAverageTooltipAttribute()
    // {
    //     $average = Average::all()->where('realtrim', $this->realtrim)->where('year',$this->RealYear)->last();
    //     $tooltip = 'N/A';
    //     if ($average == null || $average->promedio_ml==0) {
    //         $tooltip = 'N/A';
    //     }else{
    //         $qty=0;
    //         $average->promedio_ml = round(($average->promedio_ml),2);
    //         $tooltip = '$'.number_format ( $average->promedio_ml, 2 , "," , "." ).' ('.$average->qty_ml.')';
    //     }
    //     return  $tooltip;
    // }
    // public function getMlAverageKMAttribute()
    // {
    //     $rangekm=0;
    //     $return = 'N/A';
    //     $average = Average::all()->where('realtrim', $this->realtrim)->where('year',$this->RealYear)->last();
    //     if($average!=null){
    //         $Ranges=Range::all()->where('average_id',$average['id']);
    //         foreach ($Ranges as $Range) {
    //             if($this->RealKM > $Range->min && $this->RealKM < $Range->max){
    //                 $rangekm=$Range->average;
    //             }
    //         }
    //     }
    //     if ($rangekm!=0) {
    //         $averagekm=$rangekm;
    //         $price =  $this->price;
    //         $return = ((round(($price*100)/$averagekm))-100).'%';
    //     }
    //     return  $return;
    // }
    // public function getMlAverageKMTooltipAttribute()
    // {
    //     $rangekm=0;
    //     $rangeqty=0;
    //     $rangemin=0;
    //     $rangemax=0;
    //     $tooltip = 'N/A';
    //     $average = Average::all()->where('realtrim', $this->realtrim)->where('year',$this->RealYear)->last();
    //     if($average!=null){
    //         $Ranges=Range::all()->where('average_id',$average['id']);
    //         foreach ($Ranges as $Range) {
    //             if($this->RealKM > $Range->min && $this->RealKM < $Range->max){
    //                 $rangekm=$Range->average;
    //                 $rangeqty=$Range->qty;
    //                 $rangemin=round(($Range->min/1000),0);
    //                 $rangemax=round(($Range->max/1000),0);
    //             }
    //         }
    //     }
    //     if ($average == null || $rangekm==0) {
    //         $tooltip = 'N/A';
    //     }else{
    //             $qty=0;
    //             $rangekm = round(($rangekm),2);
    //             $tooltip = '<em>'.$rangemin.'milKM</em> ~ <em>'.$rangemax.'milKM</em> <br>$'.number_format ( $rangekm, 2 , "," , "." ).' ('.$rangeqty.')';
    //     }
    //     return  $tooltip;
    // }

    // public function getMotorAverageAttribute()
    // {

    //     $average = Average::all()->where('realtrim', $this->realtrim)->where('year',$this->RealYear)->last();
    //     $return = 'N/A';
    //     if ($average == null || $average->promedio_motor==0) {
    //         $return = 'N/A';

resources/views/admin/publications/index.blade.php
@extends('layouts.backend')

@section('content')
    <link rel="stylesheet" type="text/css" href="/css/custom-mia-dataTable.css">
    <!-- Hero -->
    <div class="bg-body-light">
        <div class="content content-full">
            <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
                <h1 class="flex-sm-fill h3 my-2">
                    @if(isset($Groupname))
                        {{$Groupname}}
                    @else
                        Publicaciones 
                    @endif
                </h1>
                <nav class="flex-sm-00-auto ml-sm-3" aria-label="breadcrumb">
<!--                     <ol class="breadcrumb breadcrumb-alt">
                        <li class="breadcrumb-item">
                            <a href="/dash/search/" class="link-fx btn btn-sm btn-outline-primary">Hacer una búsqueda</a>
                        </li>
                        <li class="breadcrumb-item" aria-current="page">
                            <a class="link-fx btn btn-sm btn-primary" href="/dash/publication/newcreate">Crear una Consulta (ML)</a>
                        </li>
                    </ol> -->
                </nav>
            </div>
        </div>
    </div>
    <!-- END Hero -->

     <!-- Page Content -->
    <div class="content" style="    overflow:hidden;">
        <!-- Dynamic Table Full -->
        <div class="block">
            <div class="block-header">
                <h3 class="block-title">Publicaciones <small></small></h3>
            </div>
            <div class="block-content block-content-full">
                <!-- DataTables init on table by adding .js-dataTable-full class, functionality is initialized in js/pages/be_tables_datatables.min.js which was auto compiled from _es6/pages/be_tables_datatables.js -->
                @if (session('message'))
                    <div class="alert alert-success">
                        {{ session('message') }}
                    </div>
                @endif
                <!-- Bloque de opciones --> 
                <div class="block-options-dataTable">
                    <div class="tittle-option">Vistas</div>
                    <div class="buttons-option">
                        <button href="#" class="btn btn-sm btn-outline-danger"  
                            custom-filter='[Retraso|moroso]' 
                            custom-filter-column='7' 
                            custom-sort='asc' 
                            custom-sort-column='6'>
                            Cartera Vencida
                        </button>                  
                    </div>
                </div> 

                <table class="table table-bordered table-striped table-vcenter init-dataTable">
                    <thead>
                        <tr>
                            <th filter-type ='range_number_slider'> <span class="title-head">Barometro</span> </th>
                            <th filter-type ='multi_select'> <span class="title-head">Marca</span> </th>
                            <th filter-type ='multi_select'> <span class="title-head">Modelo</span> </th>
                            <th filter-type ='text'> <span class="title-head">Versión</span> </th>
                            <th filter-type ='multi_select'> <span class="title-head">Año</span> </th>
                            <th filter-type ='range_number_slider'> <span class="title-head">TOTAL ML</span> </th>
                            <th filter-type ='range_number_slider'> <span class="title-head">ML KM</span> </th>
                            <th filter-type ='range_number'> <span class="title-head">%KM</span> </th>
                            <th filter-type ='range_number'> <span class="title-head">Rango KM</span> </th>
                            <th filter-type ='multi_select'> <span class="title-head">Dpto.</span> </th>
                            <th filter-type ='range_number_slider'> <span class="title-head">Precio</span> </th>
                            <th> <span class="title-head">Promedio de la version/año</span> </th>
                            <th> <span class="title-head">Promedio del rango KM</span> </th>
                            <th filter-type ='range_number_slider'> <span class="title-head">MOTOR</span> </th>
                            <th> <span class="title-head">Promedio Motor</span> </th>
                            <th> <span class="title-head">Kilometraje Esperado</span> </th>
                            
                            <th >Acciones</th>
                        </tr>
                    </thead> 
                    <tbody>
                        @forelse($Publications as $Publication)
                            <tr>
                                <td class="font-size-sm">
                                    <br>
                                    <span>@if(isset($Publication->barometro)) {{$Publication->barometro}} @else ml_average_tooltip Error @endif</span>
                                </td>
                                <td class="font-w600 font-size-sm">
                                    <span style="font-size: 11px">@if(isset($Publication->BRAND)) {{$Publication->BRAND }} @else Brand Error @endif</span>
                                </td>
                                <td class="font-w600 font-size-sm">
                                    <span style="font-size: 11px">@if(isset($Publication->MODEL)) {{$Publication->MODEL }} @else Model Error @endif</span>
                                </td>
                                <td class="font-size-sm">
                                    <span style="font-size: 10px">@if(isset($Publication->RealVersion)) @if(isset($Publication->JustTrim)) {{$Publication->JustTrim }} @else -- @endif  @else   Version Error   @endif</span>
                                </td>
                                <td class="font-size-sm">
                                    <span>@if(isset($Publication->VEHICLE_YEAR)) {{$Publication->VEHICLE_YEAR }}  @else  Year Error   @endif</span>
                                </td> 
                                <td class="font-size-sm">
                                    <span>
                                    @if(isset($Publication->histories->last()->ml_average))
                                        @if($Publication->histories->last()->ml_average!="N/A")
                                        {{$Publication->histories->last()->ml_average }}% 
                                        @else
                                        0%
                                        @endif
                                    @else  
                                        ml_average Error 
                                    @endif
                                    </span>
                                </td>
                                <td class="font-size-sm"> 
                                    <span>
                                    @if(isset($Publication->histories->last()->ml_average_km))
                                        @if($Publication->histories->last()->ml_average_km!="N/A")
                                        {{$Publication->histories->last()->ml_average_km }}% 
                                        @else
                                        0%
                                        @endif
                                    @else  
                                        ml_average_km Error 
                                    @endif
                                    </span>
                                </td>
                                
                                <td class="font-size-sm">
                                    <span>
                                    @if(isset($Publication->histories->last()->average_expected_km))
                                        @if($Publication->histories->last()->average_expected_km!="N/A")
                                        {{$Publication->histories->last()->average_expected_km }}% 
                                        @else
                                        0%
                                        @endif
                                    @else  
                                        average_expected_km Error 
                                    @endif
                                    </span>
                                </td>
                                <td class="font-size-sm">
                                    <span>@if(isset($Publication->RealRange)) {{$Publication->RealRange}} @else RealRange Error @endif</span>
                                </td>
                                <td class="font-size-sm">
                                    <span style="font-size: 10px">@if(isset($Publication->state_name)) {{$Publication->state_name}} @else state_name Error @endif</span>
                                </td>
                                <td class="font-size-sm">
                                    <span style="font-size: 10px">@if(isset($Publication->price)) {{$Publication->Realprice}} @else Price Error @endif</span>
                                </td>
                                <td class="font-size-sm">
                                    <br>
                                    <span>@if(isset($Publication->histories->last()->ml_average_tooltip)) {!!$Publication->histories->last()->ml_average_tooltip!!} @else ml_average_tooltip Error @endif</span>
                                </td>
                                <td class="font-size-sm">
                                    <br>
                                    <span>@if(isset($Publication->histories->last()->ml_average_km_tooltip)) {!!$Publication->histories->last()->ml_average_km_tooltip!!} @else ml_average_tooltip Error @endif</span>
                                </td>
                                <td class="font-size-sm">
                                    <span>@if(isset($Publication->histories->last()->motor_average)) {{$Publication->histories->last()->motor_average }}% @else  motor_average Error  @endif</span>
                                </td>
                                <td class="font-size-sm">
                                    <br>
                                    <span>@if(isset($Publication->histories->last()->motor_average_tooltip)) {!!$Publication->histories->last()->motor_average_tooltip!!} @else ml_average_tooltip Error @endif</span>
                                </td>
                                <td class="font-size-sm">
                                    <br>
                                    <span>@if(isset($Publication->histories->last()->average_expected_km_tooltip)) {!!$Publication->histories->last()->average_expected_km_tooltip!!} @else ml_average_tooltip Error @endif</span>
                                </td>

                                <td style="">
                                    <br>
                                    @if(isset($Publication->permalink)) 
                                    <br>
                                        <a   style="width: 200px" class="btn btn-success" href="{{$Publication->permalink}}" target="_blank">Mercado Libre</a> 
                                    @else @endif
                                    <br>
                                    <br>
                                     <!-- <a href="/dash/publications/{{$Publication->id}}/edit"  style="width: 200px"   class="btn btn-warning">VER</a> -->
                                    <a href="/dash/publication/{{$Publication->id}}/deleting" style="width: 200px" class=" btn btn-danger">Eliminar</a> 
                                    <br><br>
                                    <a href="/dash/publication/{{$Publication->id}}/sold" style="width: 200px" class=" btn btn-warning">Vendido</a> 

                                </td>
                            </tr>
                        @empty
                            <tr>
                                <td class="text-center font-size-sm">#</td>
                                <td class="font-w600 font-size-sm"><a >No hay adopciones registradas</a></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                            </tr>
                        @endforelse
                    </tbody>
                </table> 
            </div>
        </div>
        <!-- END Dynamic Table Full -->
    </div>
    <!-- END Page Content --> 
@endsection 
@section('js_tabla')
    <script src="/js/custom-mia-dataTable.js"></script>  
    <script type="text/javascript">
        $(document).ready(function () {
            'use strict';   
            var oTables = smartInitDateTable(); 
        });
    </script> 
@endsection

resources/views/admin/publications/search.blade.php
@extends('layouts.backend')

@section('content')
    <!-- Hero -->
    <!-- END Hero -->

 <!-- Page Content -->
<div class="content">


    <!-- Alternative Style -->
    <div class="block">
        <div class="block-header">
            <h3 class="block-title">Buscar Publicaciones</h3>
        </div>
        <div class="block-content block-content-full">
            @if ($errors->any())
            <ul class="alert alert-danger">
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
            @endif



            <form action="/dash/publications/search" method="POST" validate=true>
                {{ csrf_field() }}
                <div class="row">
                    <div class="col-lg-4">
                        <p class="font-size-sm text-muted">
                            Escoge Marca, Modelo y Versión para buscar resultados. 
                        </p>
                    </div>
                    <div class="col-lg-8 col-xl-5">
                        <div class="form-group">
                            <label for="name">Marcas</label>
                            <select name="brand" id="brand" class="js-select2 form-control">
                                <option value="0">Selecciona una marca</option>
                            @foreach($Marcas as $Marca)
                                <option value="{{$Marca['value_name']}}" >{{$Marca['value_name']}}</option>
                            @endforeach
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="name">Modelo</label>
                            <select name="model" id="model" class="js-select2 form-control">
                                <option value="0">Selecciona una marca primero</option>
                            </select>
                        </div>                     
                        <button type="success" class="btn btn-primary">Buscar Publicaciones</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <!-- END Alternative Style -->

</div>
<!-- END Page Content -->


@endsection
@section('js_after')

<script type="text/javascript">

    $(function(){


        $("#brand").change(function(){
            $('#model').html('<option value="0">Cargando</option>');
            var brand = $(this).children("option:selected").val();
            $.ajaxSetup({
                headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')}
            });
            $.ajax({
                url: "/dash/models/brand/"+brand+"",
                method: 'GET',
                data: {
                    brand: brand,
                },
                success: function(result){
                    console.log(result);
                    $('#model').html('<option value="0">Selecciona un modelo</option>');
                    var models = JSON.parse(result);
                    $.each( models, function( key, value ) {
                        $('#model').append(new Option(value, value));
                    });
                }
            });

        });

    });

</script>

@endsection